### ISSUE TITLE
php artisan fails to serve, and admin page not accessible from xampp server

### ISSUE THREAD

**Issue by creativebash** [AhmedYahyaE/laravel-multi-vendor-e-commerce-application#1]
![php artisan fails](https://github.com/AhmedYahyaE/laravel-multi-vendor-e-commerce-application/assets/7485175/fba720a1-0b33-4aa5-918c-82664fa904a2)

but with xampp, the homepage is accessible from http://localhost/[multi-vendor]/public, however there is no way to get to the admin page.

**Comment by AhmedYahyaE** [comment]
@creativebash
Please follow the 'Installation & Configuration' section in the REAME.md file carefully! You have to create your MySQL database and make sure to import its SQL dump file FIRST, then configure the .env file accordingly! After that, run the 'php artisan serve' command from the root directory (not from the public folder) of the project (as with any other Laravel project). Everything should be fine then!

**Comment by AhmedYahyaE** [comment]
@creativebash Please try the solution and confirm!

**Comment by creativebash** [comment]
I followed the instructions. here is a screen recording

https://github.com/AhmedYahyaE/laravel-multi-vendor-e-commerce-application/assets/7485175/ffd18f90-79db-418a-9c8a-bed37910a63c

**Comment by AhmedYahyaE** [comment]
Can you show me your database? PhpMyAdmin?

**Comment by creativebash** [comment]
![screencapture-localhost-phpmyadmin-index-php-2023-09-06-07_33_43](https://github.com/AhmedYahyaE/laravel-multi-vendor-e-commerce-application/assets/7485175/2216a651-8d56-4c94-b8ed-ff0ec0af2e67)
