### ISSUE TITLE
CANNOT REGISTER AS A USER

### ISSUE THREAD

**Issue by bajwa4200** [AhmedYahyaE/laravel-multi-vendor-e-commerce-application#2]
When i try to checkout it asks for me to login or register i tried registering but it gives me error

**Comment by AhmedYahyaE** [comment]
Could you provide a screenshot of the error?

**Comment by AhmedYahyaE** [comment]
@bajwa4200 Could you provide a screenshot of the error?

**Comment by AhmedYahyaE** [comment]
@bajwa4200 Fixed the issue in the database SQL dump file. Please remove (drop) your current database, then download again the updated database SQL dump file (refer back to the Installation & Configuration section in the README.md file) and import it.
